### ISSUE TITLE
having issues setting up a new homestead No such file or directory

### ISSUE THREAD

**Issue by manshoor** [svpernova09/homestead#6]
- Vagrant: 2.4.1
  - Provider: Virtualbox
  - Homestead: release

## Host operating system
iMac Intel macos sonoma 14.6.1

## Homestead.yaml
```yaml
ip: "192.168.56.56"
memory: 4096
cpus: 2
provider: virtualbox
name: homestead
hostname: homestead
ssl: true

authorize: ~/.ssh/homesteadSSH/id_homestead.pub

keys:
  - ~/.ssh/homesteadSSH/id_homestead

folders:
  - map: /Volumes/T5/projects/office
    to: /home/vagrant/projects
    type: "nfs"

sites:
  - map: project1.local
    to: /home/vagrant/projects/project1/public_html
    php: "5.6"
    wildcard: "yes"
    use_wildcard: "no"
    params:
      - key: CI_ENV
        value: local
  ############################################################################
  - map: builder.local
    to: /home/vagrant/projects/builder-backend/public
    php: "7.2"
    params:
      - key: CI_ENV
        value: local
  - map: la.local
    to: /home/vagrant/projects/backend/admin/public_html
    php: "5.6"
    wildcard: "yes"
    use_wildcard: "no"
    params:
      - key: CI_ENV
        value: local
  

features:
  - golang: false
  - python: false
  - webdriver: false
  - mysql: true
  - docker: false
  - mongodb: false
  - mariadb: false
  - postgresql: false
  - ohmyzsh: false

services:
    - enabled:
        - "mysql"
#    - disabled:
#        - "postgresql@11-main"

variables:
  - key: CI_ENV
    value: local
  - key: APP_ENV
    value: local


databases:
  - backend
  - builder
```

## Vagrant destroy & up output
```
homestead: /tmp/vagrant-shell: line 2: /etc/php/8.4/fpm/pool.d/www.conf: No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

## Steps to reproduce
1. creating a new setup, as I moved from laravel homestead
2. vagrant up

**Comment by coolamit** [comment]
@svpernova09 Any updates on this. This is preventing new installs.

**Comment by svpernova09** [comment]
Can you provide the full output of the vagrant up?

**Comment by josezenem** [comment]
@manshoor @coolamit I was having a similar issue, I pushed out a pull request here: https://github.com/svpernova09/homestead/pull/10#issuecomment-2608398313 it resolved the issue for me, can you both try pulling latest and re-running vagrant destroy;vagrant up to see if it fixes your issue.

**Comment by coolamit** [comment]
@svpernova09 

Here is my Homestead.yaml file

```yaml
---
ip: "192.168.56.56"
memory: 8192
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ./code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/homestead/public

variables:
    - key: APP_ENV
      value: local
    - key: MEILI_MASTER_KEY
      value: homestead

databases:
    - homestead

buckets:
    - name: todos-bckt
      policy: public
    - name: test-me-bckt
      policy: public

features:
    - cassandra: false
    - golang: true
    - influxdb: false
    - mariadb: false
    - meilisearch: true
    - minio: true
    - mongodb: false
    - ohmyzsh: false
    - pm2: true
    - postgresql: true
    - python: true
    - rabbitmq: true
    - rustc: true
    - webdriver: true

services:
    - enabled:
        - "mysql"
#    - disabled:
#        - "postgresql@11-main"

ports:
    - send: 33060 # MySQL/MariaDB
      to: 3306
#    - send: 4040 # ngrok UI
#      to: 4040
    - send: 54320 # PostgreSQL
      to: 5432
    - send: 8025 # Mailpit
      to: 8025
    - send: 9600 # Minio
      to: 9600
    - send: 9601 # Minio
      to: 9601
    - send: 7700 # Meilisearch
      to: 7700
    - send: 8000
      to: 8000
#    - send: 27017
#      to: 27017
```

And attached is the `vagrant up --provision` output

[homestead-provision-log.txt](https://github.com/user-attachments/files/18520573/homestead-provision-log.txt)

**Comment by coolamit** [comment]
> [@manshoor](https://github.com/manshoor) [@coolamit](https://github.com/coolamit) I was having a similar issue, I pushed out a pull request here: [#10 (comment)](https://github.com/svpernova09/homestead/pull/10#issuecomment-2608398313) it resolved the issue for me, can you both try pulling latest and re-running vagrant destroy;vagrant up to see if it fixes your issue.

Didn't work for me. I pulled the latest from `main` branch & ran `vagrant up --provision` but I still get same error

```
/etc/php/8.4/fpm/pool.d/www.conf: No such file or directory
```

**Comment by svpernova09** [comment]
> > [@manshoor](https://github.com/manshoor) [@coolamit](https://github.com/coolamit) I was having a similar issue, I pushed out a pull request here: [#10 (comment)](https://github.com/svpernova09/homestead/pull/10#issuecomment-2608398313) it resolved the issue for me, can you both try pulling latest and re-running vagrant destroy;vagrant up to see if it fixes your issue.
> 
> Didn't work for me. I pulled the latest from `main` branch & ran `vagrant up --provision` but I still get same error
> 
> ```
> /etc/php/8.4/fpm/pool.d/www.conf: No such file or directory
> ```

You're not providing what I'm asking for and you're not running the commands being asked of you.

Please do these things:

- [ ] Run vagrant destroy.
- [ ] Run vagrant up.
- [ ] Post a gist of the full output of this new vagrant up command.

**Comment by coolamit** [comment]
> > > [@manshoor](https://github.com/manshoor) [@coolamit](https://github.com/coolamit) I was having a similar issue, I pushed out a pull request here: [#10 (comment)](https://github.com/svpernova09/homestead/pull/10#issuecomment-2608398313) it resolved the issue for me, can you both try pulling latest and re-running vagrant destroy;vagrant up to see if it fixes your issue.
> > 
> > 
> > Didn't work for me. I pulled the latest from `main` branch & ran `vagrant up --provision` but I still get same error
> > ```
> > /etc/php/8.4/fpm/pool.d/www.conf: No such file or directory
> > ```
> 
> You're not providing what I'm asking for and you're not running the commands being asked of you.
> 
> Please do these things:
> 
> * [ ]  Run vagrant destroy.[ ]  Run vagrant up.[ ]  Post a gist of the full output of this new vagrant up command.

Here - https://github.com/svpernova09/homestead/issues/6#issuecomment-2609721355

I already did that, probably skipped your notice as you just looked at the last comment. :)

**Comment by coolamit** [comment]
Sure. Is there a way to rename the box to something other than `homestead`? I just provisioned `laravel/homestead` for a project & I'd rather not destroy that & set it up again.

**Comment by josezenem** [comment]
This repo here has its own box called Svpernova09/homestead, so both will run side by side.  If you make a different directory for this homestead with its own settings, it should spin up independently then your other one, just make sure to do a vagrant halt on the first one.  Just make sure you only run one at a time to avoid any issues, and change the IP in the Vagrant file, I usually just change the last number and increase/decrease by 1.

```
➜  ~ vagrant box list
Svpernova09/homestead (parallels, 14.1.0, (arm64))
laravel/homestead     (parallels, 14.0.2, (arm64))
```

**Comment by svpernova09** [comment]
If you're using my fork, you must use `Svpernova09/homestead`. If you're setting a `box:` in `Homestead.yaml,` you can remove it from the file, and the project will use the correct base box.

**Comment by svpernova09** [comment]
> [@svpernova09](https://github.com/svpernova09) And here is the Gist if you prefer that instead of the text file of the log that I attached to [#6 (comment)](https://github.com/svpernova09/homestead/issues/6#issuecomment-2609721355)
> 
> https://gist.github.com/coolamit/26087283528596cac1d2a3cc7e86e3ec
> 
> Thanks for looking into it.

These are logs from `vagrant --provision`, which is *not* the same as a `vagrant destroy; vagrant up.` 

This version currently has PHP 8.3 as the default; if you want 8.4, you must put it on the site as [previously stated](https://github.com/svpernova09/homestead/issues/6#issuecomment-2610696991)

I am closing this as I believe the original issue is resolved in the `main` branch.

**Comment by coolamit** [comment]
> If you're using my fork, you must use `Svpernova09/homestead`. If you're setting a `box:` in `Homestead.yaml,` you can remove it from the file, and the project will use the correct base box.

I have this repo cloned in a separate folder. The Homestead.yaml file does not have `box` in it. And here is what I get on doing `vagrant up` after `vagrant destroy`

```bash
vagrant up
Bringing machine 'homestead' up with 'virtualbox' provider...
==> homestead: Importing base box 'Svpernova09/homestead'...
==> homestead: Matching MAC address for NAT networking...
==> homestead: Checking if box 'Svpernova09/homestead' version '14.1.0' is up to date...
A VirtualBox machine with the name 'homestead' already exists.
Please use another name or delete the machine with the existing
name, and try again.
```

Here's the `Homestead.yaml` file I'm using

```yaml
---
ip: "192.168.56.57"
memory: 8192
cpus: 2
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ./code
      to: /home/vagrant/code

sites:
    - map: homestead.test
      to: /home/vagrant/code/homestead/public
      php: "8.4"

variables:
    - key: APP_ENV
      value: local
    - key: MEILI_MASTER_KEY
      value: homestead

databases:
    - homestead

buckets:
    - name: todos-bckt
      policy: public
    - name: test-me-bckt
      policy: public

features:
    - cassandra: false
    - golang: true
    - influxdb: false
    - mariadb: false
    - meilisearch: true
    - minio: true
    - mongodb: false
    - ohmyzsh: false
    - pm2: true
    - postgresql: true
    - python: true
    - rabbitmq: true
    - rustc: true
    - webdriver: true

services:
    - enabled:
        - "mysql"
        - "postgresql"
#    - disabled:
#        - "postgresql@11-main"

ports:
    - send: 33060 # MySQL/MariaDB
      to: 3306
#    - send: 4040 # ngrok UI
#      to: 4040
    - send: 54320 # PostgreSQL
      to: 5432
    - send: 8025 # Mailpit
      to: 8025
    - send: 9600 # Minio
      to: 9600
    - send: 9601 # Minio
      to: 9601
    - send: 7700 # Meilisearch
      to: 7700
    - send: 8000
      to: 8000
#    - send: 27017
#      to: 27017
```
