### ISSUE TITLE
Using libvirt as provider

### ISSUE THREAD

**Issue by psion** [svpernova09/homestead#7]
Please note that the Homestead issue tracker is reserved for bug reports and enhancements. We are not always able to debug Vagrant, Provider or Operating System issues, but will do our best to help. Thank you!

## Versions
Latest

## Host operating system
ArchLinux

## Homestead.yaml
```yaml
# Relevant portion of Homestead.yaml
memory: 2048
cpus: 2
provider: libvirt
hostname: homestead
```

## Vagrant destroy & up output
(https://gist.github.com/psion/c60ad2fda507289317d8a3a0307ffeb8)

## Expected behavior
It should download the image, but the image does not exist under username Svpernova09

## Actual behavior
It failed and wouldn't download

## Steps to reproduce
1. Change provider to libvirt
2. vagrant up
